# Generated by Django 3.0.4 on 2020-03-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=6)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('would_take_again', models.BooleanField(default=False)),
                ('comments', models.TextField()),
                ('overall', models.IntegerField(default=0)),
                ('P_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Professor')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Course')),
            ],
        ),
    ]
