# Generated by Django 3.0.4 on 2020-03-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('AM', 'Applied Mechanics'), ('BB', 'Biochemical Engineering and Biotechnology'), ('CH', 'Chemical Engineering'), ('CE', 'Civil Engineering'), ('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering')], max_length=2),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(choices=[('AM', 'Applied Mechanics'), ('BB', 'Biochemical Engineering and Biotechnology'), ('CH', 'Chemical Engineering'), ('CE', 'Civil Engineering'), ('CS', 'Computer Science and Engineering'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering')], max_length=2),
        ),
    ]
